"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Imdb_1 = require("./Imdb");
var movie_1 = require("./movie");
var professional_1 = require("./professional");
var fs = require("fs");
var readlineSync = require("readline-sync");
var pelicula = new movie_1.Movie("El patriota", 2005, "Estados Unidos", "Belica");
var pelicula1 = new movie_1.Movie("Doraemon", 1990, "Japonesa", "Animada");
var pelicula2 = new movie_1.Movie("Star War", 1980, "Estados Unidos", "Ciencia Ficcion");
var name = readlineSync.question("name");
var age = readlineSync.question("age");
var weight = readlineSync.question("weight");
var height = readlineSync.question("height");
var isRetired = readlineSync.question("isRetired");
var nationality = readlineSync.question("nationality");
var oscarnumber = readlineSync.question("oscarnumber");
var profession = readlineSync.question("profession");
var newProfesional = new professional_1.Professional(name, age, weight, height, isRetired, nationality, oscarnumber, profession);
console.log(newProfesional);
var peliculas = [pelicula, pelicula1, pelicula2];
var imdb = new Imdb_1.Imdb(peliculas);
var imdbString = JSON.stringify(imdb);
fs.writeFileSync("IMBD.json", imdbString);
console.log(imdbString);
//console.log(imdb.escribirEnFicheroJSON("pruebafinal.ts"));
imdb.escribirEnFicheroJSON("./jesusyomar.json");
